spring:
  cloud:
    azure:
      eventhubs:
        connection-string: Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=EMULATOR_DEV_SAS_VALUE
        processor:
          checkpoint-store:
            container-name: eventhub-binder-app
            account-name: devstoreaccount1
            account-key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
            endpoint: http://127.0.0.1:10000/devstoreaccount1
            create-container-if-not-exists: true
    function:
      definition: consume;supply
    stream:
      bindings:
        consume-in-0:
          destination: eh1
          group: cg1
          consumer:
            batch-mode: true
        supply-out-0:
          destination: eh1 # same as the above destination
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              batch:
                max-size: 10 # The default value is 10
                max-wait-time: 1m # Optional, the default value is null
              checkpoint:
                mode: BATCH
      default:
        producer:
          errorChannelEnabled: true
      poller:
        initial-delay: 0
        fixed-delay: 1000
