spring:
  cloud:
    azure:
      eventhubs:
        event-hub-name: eh1
        consumer:
          consumer-group: $Default
        connection-string: Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=EMULATOR_DEV_SAS_VALUE
